// Generated by src/cltl/annotation/generate_dropdown_values.py from src/cltl/data_type.py.
// Do not edit by hand — change the enums in data_type.py and re-run the generator instead.
const ACTIVITY_TYPES = ["advise", "diet", "disease", "exercise", "measurement", "medicine", "mental condition", "physical condition", "social", "social condition", "symptom", "take_drink", "take_food", "treatment", "other"];
const ROLE_TYPES = {"default": ["person", "group", "organization", "object", "substance", "vehicle", "tool", "place", "city", "country", "indoor", "outdoor", "other"], "result": ["goal", "impact"]};
const CERTAINTY_VALUES = ["certain", "uncertain", "neutral"];
const DEFAULT_CERTAINTY = "neutral";
const FACTUALITY_VALUES = ["confirm", "deny", "expect"];
const DEFAULT_FACTUALITY = "confirm";
const DEFAULT_EMOTION = "neutral";
const GO_EMOTION_GROUPS = {"positive": ["admiration", "amusement", "approval", "caring", "curiosity", "desire", "excitement", "gratitude", "joy", "love", "optimism", "pride", "relief"], "negative": ["anger", "annoyance", "confusion", "disappointment", "disapproval", "disgust", "embarrassment", "fear", "grief", "nervousness", "remorse", "sadness"], "ambiguous": ["realization", "surprise"]};
const TEMPORAL_TYPES = ["point", "range", "duration", "recurring", "vague"];
const DEFAULT_TEMPORAL_TYPE = "range";
const RECURRENCE_PATTERNS = ["daily", "regularly", "often", "now-and-then", "sometimes", "rarely"];
