"""
Regenerates dropdown_values.js from the enums in src/cltl/data_type.py, so the
annotation tool's dropdowns, the LLM prompt and the Pydantic models all draw
on the same closed vocabularies. Run this after changing any enum in
data_type.py (ActivityType, RoleType, ResultType, EmotionLabel, Factuality,
Certainty, TemporalType, RecurrencePattern, EMOTION_GROUPS, ROLE_TYPES).
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import data_type

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "dropdown_values.js")


def _values(enum_cls):
    return [member.value for member in enum_cls]


def _alphabetical_other_last(values):
    """Dropdown display order: alphabetical, with "other" (if present) pinned last."""
    return sorted((v for v in values if v != "other")) + (["other"] if "other" in values else [])


def main():
    constants = {
        "ACTIVITY_TYPES": _alphabetical_other_last(_values(data_type.ActivityType)),
        "ROLE_TYPES": {
            "default": _values(data_type.ROLE_TYPES["default"]),
            "result": _values(data_type.ROLE_TYPES["result"]),
        },
        "CERTAINTY_VALUES": _values(data_type.Certainty),
        "DEFAULT_CERTAINTY": data_type.DEFAULT_CERTAINTY.value,
        "FACTUALITY_VALUES": _values(data_type.Factuality),
        "DEFAULT_FACTUALITY": data_type.DEFAULT_FACTUALITY.value,
        "DEFAULT_EMOTION": data_type.DEFAULT_EMOTION.value,
        "GO_EMOTION_GROUPS": {
            "positive": _values(data_type.EMOTION_GROUPS["positive"]),
            "negative": _values(data_type.EMOTION_GROUPS["negative"]),
            "ambiguous": _values(data_type.EMOTION_GROUPS["ambiguous"]),
        },
        "TEMPORAL_TYPES": _values(data_type.TemporalType),
        "DEFAULT_TEMPORAL_TYPE": data_type.TemporalType.range.value,
        "RECURRENCE_PATTERNS": _values(data_type.RecurrencePattern),
    }

    lines = [
        "// Generated by src/cltl/annotation/generate_dropdown_values.py from src/cltl/data_type.py.",
        "// Do not edit by hand — change the enums in data_type.py and re-run the generator instead.",
    ]
    for name, value in constants.items():
        lines.append(f"const {name} = {json.dumps(value)};")

    with open(OUTPUT_PATH, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()